# Generated by Django 5.0.6 on 2024-07-01 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='publisehd_date',
            new_name='publish_date',
        ),
    ]
